controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
